[GLOBAL]
pants_version = "2.1.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.flake8"
]

[source]
# The Python source root is the repo root. See https://www.pantsbuild.org/docs/source-roots.
root_patterns = ["/"]

[python-setup]
# The default interpreter compatibility for code in this repo. Individual targets can override
#  this with the `interpreter_constraints` field. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility.
interpreter_constraints = ["==2.7.*", ">=3.6"]
# Use a constraints file. See https://www.pantsbuild.org/docs/python-third-party-dependencies.
requirement_constraints = "constraints.txt"
# We search for interpreters on both on the $PATH and in the `$(pyenv root)/versions` folder.
#  If you're using macOS, you may want to leave off the <PATH> entry to avoid using the
#  problematic system Pythons. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
interpreter_search_paths = ["<PATH>", "<PYENV>"]

[flake8]
config = "build-support/.flake8"

[pytest]
version = "pytest>=4.0,<6.1"
pytest_plugins = ["zipp>=1.2"]
